name = "EaRyd"
uuid = "919886a7-1033-42c4-9b63-e090dad94c32"
authors = ["Roger-Luo <rogerluo.rl18@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ContinuousEmulator = "10fc086f-8aaa-4f44-9b62-28c43ef0af29"
CuRydbergEmulator = "6b142359-0b0c-4dfb-9c9b-84981bce612e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
RydbergEmulator = "12dc9fdf-52a0-4520-b7fc-d1c1ff3ad2fe"

[compat]
julia = "1.6.3"
Reexport = "1"
ContinuousEmulator = "0.4"
CuRydbergEmulator = "0.2"
RydbergEmulator = "0.14"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
