name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  test:
    runs-on: [self-hosted, linux, x64]
    strategy:
      matrix:
        julia-version: ['1.5']
        julia-arch: [x64]
    
    steps:
      - uses: actions/checkout@v1.0.0
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: "Add Registry"
        run: julia -e 'using Pkg; pkg"registry add https://DrHenryArmitage:${{ secrets.CI_TOKEN }}@github.com/Happy-Diode/Miskatonic.git"'
      - name: "Test Package"
        run: julia --color=yes --check-bounds=yes --project -e 'using Pkg; Pkg.test(coverage=true)'
        shell: bash
      - name: "Submit Codecov"
        run: COVERALLS_TOKEN=fhOq6SynDoIJC01GwNBNCfVBpCRnPnCEo julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
